name: Shellcheck

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - uses: reviewdog/action-shellcheck@v1
      with:
        reporter: github-pr-review
        check_all_files_with_shebangs: "false"
