name: Test

on:
  pull_request:
    paths:
      - .github/workflows/test.yml
      - bin/**
      - cookbooks/**
      - lib/**
      - nodes/**
      - roles/**
      - setup.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: ["macos-26", "xcode-27"]

    runs-on: ${{ matrix.os }}

    name: Test on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Test run
      run: ./setup.sh -n --node-json nodes/github-actions.json
